### ISSUE TITLE
Insufficient guide in README

### ISSUE THREAD

**Issue by TheStrangerDoctor** [aithedev/OpenSea-Twitter-Scraper#2]
Hello, this can be a good project but I believe you are missing a ton of guides in README file. This can be tough for people to understand your project. Do consider cleaning up your README file and make it clear for others to follow. You may list down the steps one by one rather than representing them in video form which can be hard to see what you are trying to do. Thank you!

**Comment by aithedev** [comment]
YOU ARE A FUCKING RETARD THATS WHY
